<?php
if ( ! defined( 'ABSPATH' ) ) exit;

function smt_solution_catalog() {
  return array(
    'managed-print-services' => array('icon'=>'fa-print','title'=>'Managed Print Services','tagline'=>'Control print costs. Improve uptime. Simplify fleet management.','intro'=>'A data-led service that assesses, optimizes, monitors, and supports your complete print environment under clear service levels and predictable costs.','challenges'=>array('Uncontrolled print expenditure and limited cost visibility','Mixed device fleets with inconsistent service and supplies','Frequent downtime and reactive support','Security and sustainability risks across the print environment'),'features'=>array('Fleet assessment and right-sizing','Remote monitoring and meter collection','Automated toner replenishment','Preventive maintenance and SLA management','Secure print and user policies','Usage reporting and continuous optimization'),'benefits'=>array('Lower total printing cost','Higher device availability','Predictable operating expenditure','Reduced administrative workload','Improved print security','Less waste and lower environmental impact')),
    'enterprise-printing' => array('icon'=>'fa-building','title'=>'Enterprise Printing Solutions','tagline'=>'Reliable output for demanding business environments.','intro'=>'Business printers, multifunction devices, production systems, and secure print technologies selected around workload, workflow, and lifecycle requirements.','challenges'=>array('Devices that cannot handle actual business workloads','High consumable and maintenance costs','Inconsistent output quality','Limited security, mobility, and finishing capabilities'),'features'=>array('Office printers and multifunction devices','Departmental and production printing','Secure and mobile printing','Scanning and document capture','Finishing and workflow options','Deployment, configuration, and training'),'benefits'=>array('Reliable business continuity','Consistent professional output','Improved user productivity','Lower lifecycle cost','Stronger document security','Scalable fleet architecture')),
    'document-management' => array('icon'=>'fa-file-lines','title'=>'Document Management','tagline'=>'Turn documents into controlled digital workflows.','intro'=>'Capture, classify, store, retrieve, route, and protect business information through structured document management and workflow automation.','challenges'=>array('Slow paper-based approvals and manual filing','Difficulty finding documents and controlling versions','Compliance and retention risks','Disconnected information across departments'),'features'=>array('Document capture and OCR','Digital archiving and indexing','Workflow and approval automation','Version and access control','Retention and audit trails','Integration with business applications'),'benefits'=>array('Faster access to information','Shorter approval cycles','Reduced paper and storage cost','Improved compliance','Better collaboration','Secure business continuity')),
    'it-infrastructure' => array('icon'=>'fa-server','title'=>'IT Infrastructure','tagline'=>'A secure and scalable foundation for business growth.','intro'=>'Design, supply, implementation, and support for servers, storage, networks, endpoints, virtualization, backup, and business continuity.','challenges'=>array('Aging infrastructure and performance bottlenecks','Unplanned downtime and weak resilience','Capacity limitations and fragmented vendors','Inadequate backup and recovery readiness'),'features'=>array('Servers, storage, and virtualization','LAN, WAN, wireless, and structured cabling','Endpoint and workplace infrastructure','Backup and disaster recovery','Monitoring and capacity planning','Deployment, migration, and support'),'benefits'=>array('Higher availability','Improved performance','Scalable capacity','Reduced operational risk','Simpler management','Stronger business continuity')),
    'cloud-microsoft-solutions' => array('icon'=>'fa-cloud','title'=>'Cloud & Microsoft Solutions','tagline'=>'Enable secure work, collaboration, and continuity from anywhere.','intro'=>'Microsoft 365, Azure, identity, migration, collaboration, backup, and cloud management services designed for modern organizations.','challenges'=>array('Legacy email and collaboration platforms','Limited remote-work capability','Identity and access complexity','Unplanned cloud cost and governance gaps'),'features'=>array('Microsoft 365 licensing and deployment','Azure infrastructure and services','Email and tenant migration','Teams and SharePoint collaboration','Identity and access management','Cloud backup, security, and governance'),'benefits'=>array('Productive hybrid work','Secure collaboration','Flexible capacity','Lower infrastructure burden','Improved continuity','Centralized identity and management')),
    'cybersecurity' => array('icon'=>'fa-shield-halved','title'=>'Cybersecurity','tagline'=>'Protect users, identities, endpoints, networks, and data.','intro'=>'Layered security solutions that reduce exposure, strengthen resilience, and help organizations manage cyber risk across their technology environment.','challenges'=>array('Growing ransomware, phishing, and account compromise','Unmanaged endpoints and weak visibility','Legacy firewalls and inconsistent security controls','Limited recovery and incident preparedness'),'features'=>array('Endpoint detection and protection','Network security and next-generation firewalls','Email and collaboration security','Identity and privileged access controls','Vulnerability assessment and hardening','Security awareness, backup, and recovery'),'benefits'=>array('Reduced attack exposure','Faster threat detection','Protected business data','Improved compliance posture','Greater operational resilience','Clearer security visibility')),
    'office-automation' => array('icon'=>'fa-gears','title'=>'Office Automation','tagline'=>'Remove repetitive work and streamline daily operations.','intro'=>'Integrated automation for forms, routing, approvals, scanning, communications, and repetitive office processes.','challenges'=>array('Manual repetitive tasks and duplicate data entry','Slow internal approvals','Paper-heavy processes','Disconnected tools and limited process visibility'),'features'=>array('Digital forms and workflow automation','Scanning and intelligent capture','Electronic approvals and notifications','Process integration and routing','Reporting and dashboards','User training and continuous improvement'),'benefits'=>array('Faster process completion','Fewer manual errors','Higher employee productivity','Improved visibility','Reduced operating cost','Consistent customer service')),
    'annual-maintenance' => array('icon'=>'fa-screwdriver-wrench','title'=>'Annual Maintenance Contracts','tagline'=>'Planned support that protects uptime and equipment value.','intro'=>'Preventive and corrective maintenance programs with agreed service levels, qualified engineers, reporting, and optional parts and consumables coverage.','challenges'=>array('Unexpected failures and operational disruption','Inconsistent repair quality and response times','No maintenance history or lifecycle planning','Uncontrolled spare parts and service costs'),'features'=>array('Preventive maintenance schedules','Corrective on-site support','SLA and escalation management','Remote diagnosis and help desk','Parts and consumables options','Service reporting and asset history'),'benefits'=>array('Higher equipment availability','Predictable support cost','Longer asset life','Faster issue resolution','Reduced operational disruption','Clear service accountability')),
  );
}

function smt_render_solution_page( $slug ) {
  $catalog = smt_solution_catalog();
  if ( empty( $catalog[$slug] ) ) return;
  $s = $catalog[$slug];
  ?>
  <main class="solution-detail-page">
    <section class="ui-page-hero solution-detail-hero"><div class="container solution-hero-grid"><div>
      <span class="eyebrow">Source More Technology</span><h1><?php echo esc_html($s['title']); ?></h1><p><?php echo esc_html($s['tagline']); ?></p>
      <div class="hero-actions"><a class="btn btn-gold" href="<?php echo esc_url(smt_page_url('contact')); ?>">Request a Consultation</a><a class="btn btn-outline" href="<?php echo esc_url(smt_page_url('solutions')); ?>">View All Solutions</a></div>
    </div><div class="solution-hero-symbol"><i class="fa-solid <?php echo esc_attr($s['icon']); ?>"></i></div></div></section>
    <section class="section"><div class="container solution-intro-grid"><div><?php smt_section_heading(array('kicker'=>'Business-focused technology','title'=>'A practical solution built around your operational needs','text'=>$s['intro'])); ?></div><aside class="solution-consult-card"><i class="fa-solid fa-comments"></i><h3>Start with an expert assessment</h3><p>We review your current environment, identify risks and opportunities, then recommend a clear implementation roadmap.</p><a href="<?php echo esc_url(smt_page_url('contact')); ?>">Talk to our experts <i class="fa-solid fa-arrow-right"></i></a></aside></div></section>
    <section class="section ui-surface-section"><div class="container"><?php smt_section_heading(array('kicker'=>'The challenge','title'=>'Common issues we help organizations solve','text'=>'Our approach begins with the business problem, not a product catalogue.')); ?><div class="solution-challenge-grid"><?php foreach($s['challenges'] as $item): ?><article class="solution-check-card reveal"><i class="fa-solid fa-triangle-exclamation"></i><p><?php echo esc_html($item); ?></p></article><?php endforeach; ?></div></div></section>
    <section class="section"><div class="container"><?php smt_section_heading(array('kicker'=>'Our solution','title'=>'Capabilities included in this service','text'=>'The final scope is tailored to your environment, priorities, and budget.')); ?><div class="solution-feature-grid"><?php foreach($s['features'] as $item): ?><article class="solution-feature-card reveal"><span><i class="fa-solid fa-check"></i></span><h3><?php echo esc_html($item); ?></h3></article><?php endforeach; ?></div></div></section>
    <section class="section ui-dark-section"><div class="container"><?php smt_section_heading(array('kicker'=>'Business outcomes','title'=>'Value you can measure','text'=>'We focus on operational, financial, security, and user-experience outcomes.','alignment'=>'center','theme'=>'dark')); ?><div class="solution-benefit-grid"><?php foreach($s['benefits'] as $item): ?><article><i class="fa-solid fa-circle-check"></i><span><?php echo esc_html($item); ?></span></article><?php endforeach; ?></div></div></section>
    <section class="section"><div class="container"><?php smt_section_heading(array('kicker'=>'How we deliver','title'=>'A controlled path from assessment to optimization','alignment'=>'center')); ?><ol class="ui-process-grid solution-process"><li><span>01</span><h3>Assess</h3><p>Understand the current environment, costs, risks, and requirements.</p></li><li><span>02</span><h3>Design</h3><p>Create the right technical and commercial solution.</p></li><li><span>03</span><h3>Implement</h3><p>Deploy with clear ownership, testing, and user readiness.</p></li><li><span>04</span><h3>Support & Optimize</h3><p>Measure results, maintain performance, and improve continuously.</p></li></ol></div></section>
    <section class="ui-cta-section"><div class="container ui-cta-inner"><div><span class="section-kicker light">Speak with our team</span><h2>Ready to improve your technology environment?</h2><p>Discuss your priorities with Source More Technology and receive a practical next-step recommendation.</p></div><div class="ui-cta-actions"><a class="btn btn-gold" href="<?php echo esc_url(smt_page_url('contact')); ?>">Book a Consultation</a></div></div></section>
  </main>
  <?php
}
