<?php get_header();
$type = isset($_GET['type']) ? sanitize_key(wp_unslash($_GET['type'])) : '';
$brand = isset($_GET['brand']) ? sanitize_title(wp_unslash($_GET['brand'])) : '';
$args = ['post_type'=>'smt_product','posts_per_page'=>12,'paged'=>max(1,get_query_var('paged'))];
if (in_array($type,['hardware','software','service'],true)) $args['meta_query']=[['key'=>'_smtp_product_type','value'=>$type]];
if ($brand) $args['tax_query']=[['taxonomy'=>'smt_product_brand','field'=>'slug','terms'=>$brand]];
$products = new WP_Query($args);
$brands = get_terms(['taxonomy'=>'smt_product_brand','hide_empty'=>true]); ?>
<main class="product-center">
<section class="ui-page-hero product-center-hero"><div class="container"><span class="eyebrow">Outright Sales & Business Software</span><h1>Product Center</h1><p>Explore business hardware, software, subscriptions, and integrated workplace technology available from Source More Technology.</p><div class="hero-actions"><a class="btn btn-gold" href="#product-grid">Browse Products</a><a class="btn btn-outline" href="<?php echo esc_url(smt_page_url('contact')); ?>">Request Sourcing Support</a></div></div></section>
<section class="section"><div class="container"><form class="product-filters" method="get"><label>Product type<select name="type"><option value="">All types</option><option value="hardware" <?php selected($type,'hardware'); ?>>Hardware</option><option value="software" <?php selected($type,'software'); ?>>Software</option><option value="service" <?php selected($type,'service'); ?>>Service / Subscription</option></select></label><label>Brand<select name="brand"><option value="">All brands</option><?php foreach($brands as $term): ?><option value="<?php echo esc_attr($term->slug); ?>" <?php selected($brand,$term->slug); ?>><?php echo esc_html($term->name); ?></option><?php endforeach; ?></select></label><button class="btn btn-primary" type="submit">Filter Products</button><a class="product-filter-reset" href="<?php echo esc_url(get_post_type_archive_link('smt_product')); ?>">Reset</a></form>
<div class="product-grid" id="product-grid"><?php if($products->have_posts()): while($products->have_posts()): $products->the_post();
$type_label=get_post_meta(get_the_ID(),'_smtp_product_type',true) ?: 'hardware'; $availability=get_post_meta(get_the_ID(),'_smtp_availability',true) ?: 'available'; $model=get_post_meta(get_the_ID(),'_smtp_model',true); ?>
<article class="product-card"><a class="product-card-image" href="<?php the_permalink(); ?>"><?php if(has_post_thumbnail()) the_post_thumbnail('medium_large'); else echo '<span class="product-placeholder"><i class="fa-solid fa-box-open"></i></span>'; ?></a><div class="product-card-body"><div class="product-card-meta"><span><?php echo esc_html(ucfirst($type_label)); ?></span><span class="availability availability-<?php echo esc_attr($availability); ?>"><?php echo esc_html(ucwords(str_replace('-',' ',$availability))); ?></span></div><h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2><?php if($model): ?><p class="product-model"><?php echo esc_html($model); ?></p><?php endif; ?><p><?php echo esc_html(get_the_excerpt()); ?></p><a class="product-card-link" href="<?php the_permalink(); ?>">View product <i class="fa-solid fa-arrow-right"></i></a></div></article>
<?php endwhile; else: ?><div class="ui-empty-state"><h2>No products found</h2><p>Try another filter or contact our team for sourcing support.</p></div><?php endif; wp_reset_postdata(); ?></div><?php the_posts_pagination(); ?></div></section>
</main><?php get_footer(); ?>
