<?php /* Template Name: Industries */
if (!defined('ABSPATH')) exit;
get_header();
$industries = smt_industry_catalog();
?>
<main class="industries-hub-page">
  <section class="ui-page-hero industries-hub-hero"><div class="container"><span class="eyebrow"><?php echo esc_html(smt_t('Sector-focused expertise','خبرات متخصصة للقطاعات')); ?></span><h1><?php echo esc_html(smt_t('Technology solutions built around the realities of your industry.','حلول تقنية مصممة حول واقع قطاعك وتحدياته.')); ?></h1><p><?php echo esc_html(smt_t('We combine enterprise technology experience with a practical understanding of operational priorities, risk, cost, governance, and service continuity.','نجمع بين الخبرة التقنية المؤسسية والفهم العملي لأولويات التشغيل والمخاطر والتكلفة والحوكمة واستمرارية الخدمة.')); ?></p><div class="hero-actions"><a class="btn btn-gold" href="<?php echo esc_url(smt_page_url('contact')); ?>"><?php echo esc_html(smt_t('Discuss Your Requirements','ناقش احتياجاتك')); ?></a><a class="btn btn-outline" href="#industry-grid"><?php echo esc_html(smt_t('Explore Industries','استكشف القطاعات')); ?></a></div></div></section>

  <section class="section" id="industry-grid"><div class="container"><?php smt_section_heading(['kicker'=>smt_t('Industries we serve','القطاعات التي نخدمها'),'title'=>smt_t('Relevant expertise for complex operating environments','خبرة مناسبة لبيئات العمل المعقدة'),'text'=>smt_t('Every engagement is shaped around your locations, users, information, security requirements, operating model, and growth plans.','نصمم كل تعاون وفق مواقعك ومستخدميك ومعلوماتك ومتطلبات الأمان ونموذج التشغيل وخطط النمو.'),'alignment'=>'center']); ?><div class="industry-hub-grid">
    <?php foreach($industries as $slug=>$industry): ?><article class="industry-hub-card reveal"><div class="industry-hub-card-head"><span><i class="fa-solid <?php echo esc_attr($industry['icon']); ?>"></i></span><small><?php echo esc_html(smt_t('Sector solutions','حلول القطاع')); ?></small></div><h2><?php echo esc_html($industry['title']); ?></h2><p><?php echo esc_html($industry['tagline']); ?></p><a href="<?php echo esc_url(smt_page_url($slug)); ?>"><?php echo esc_html(smt_t('Explore sector solutions','استكشف حلول القطاع')); ?> <i class="fa-solid fa-arrow-right"></i></a></article><?php endforeach; ?>
  </div></div></section>

  <section class="section ui-dark-section"><div class="container industry-value-layout"><div><?php smt_section_heading(['kicker'=>smt_t('One integrated partner','شريك واحد متكامل'),'title'=>smt_t('Cross-industry capabilities. Sector-specific execution.','قدرات متعددة القطاعات. تنفيذ متخصص لكل قطاع.'),'text'=>smt_t('We bring together print, documents, infrastructure, cloud, cybersecurity, software, and support—then adapt the mix to the priorities of your organization.','نجمع الطباعة والمستندات والبنية التحتية والسحابة والأمن السيبراني والبرمجيات والدعم، ثم نكيّف المزيج وفق أولويات مؤسستك.'),'theme'=>'dark']); ?></div><div class="industry-value-grid"><article><i class="fa-solid fa-chart-line"></i><strong><?php echo esc_html(smt_t('Productivity','الإنتاجية')); ?></strong><span><?php echo esc_html(smt_t('Simpler workflows and faster service','إجراءات أبسط وخدمة أسرع')); ?></span></article><article><i class="fa-solid fa-coins"></i><strong><?php echo esc_html(smt_t('Cost Control','التحكم في التكلفة')); ?></strong><span><?php echo esc_html(smt_t('Clearer lifecycle and operating cost','وضوح أكبر لتكلفة التشغيل ودورة الحياة')); ?></span></article><article><i class="fa-solid fa-shield-halved"></i><strong><?php echo esc_html(smt_t('Security','الأمان')); ?></strong><span><?php echo esc_html(smt_t('Protected users, devices, and information','حماية المستخدمين والأجهزة والمعلومات')); ?></span></article><article><i class="fa-solid fa-headset"></i><strong><?php echo esc_html(smt_t('Continuity','الاستمرارية')); ?></strong><span><?php echo esc_html(smt_t('Reliable support and resilient operations','دعم موثوق وعمليات أكثر مرونة')); ?></span></article></div></div></section>

  <section class="ui-cta-section"><div class="container ui-cta-inner"><div><span class="section-kicker light"><?php echo esc_html(smt_t('Start with an assessment','ابدأ بتقييم')); ?></span><h2><?php echo esc_html(smt_t('Let us understand your environment and priorities.','دعنا نفهم بيئة عملك وأولوياتك.')); ?></h2><p><?php echo esc_html(smt_t('We will identify the most practical opportunities to simplify operations, improve reliability, and create more value.','سنحدد أكثر الفرص عملية لتبسيط التشغيل ورفع الاعتمادية وصناعة قيمة أكبر.')); ?></p></div><div class="ui-cta-actions"><a class="btn btn-gold" href="<?php echo esc_url(smt_page_url('contact')); ?>"><?php echo esc_html(smt_t('Request a Consultation','اطلب استشارة')); ?></a></div></div></section>
</main>
<?php get_footer(); ?>
