<?php /* Template Name: Industry Detail */ if (!defined('ABSPATH')) exit; get_header();
$slug=get_post_field('post_name',get_queried_object_id());
$data=[
'banking'=>['Banking & Financial Services','البنوك والخدمات المالية','fa-building-columns','Secure, compliant and efficient document, print and IT operations for financial institutions.','عمليات مستندات وطباعة وتكنولوجيا معلومات آمنة ومتوافقة وفعّالة للمؤسسات المالية.'],
'government'=>['Government & Public Sector','القطاع الحكومي والعام','fa-landmark','Modernize citizen services and administrative operations with resilient technology.','تحديث خدمات المواطنين والعمليات الإدارية بتكنولوجيا مرنة وموثوقة.'],
'manufacturing'=>['Manufacturing','التصنيع','fa-industry','Improve uptime, workflow visibility and operational control across plants and offices.','رفع الجاهزية وتحسين وضوح سير العمل والتحكم التشغيلي في المصانع والمكاتب.'],
'healthcare'=>['Healthcare','الرعاية الصحية','fa-heart-pulse','Protect information and streamline clinical and administrative document workflows.','حماية المعلومات وتبسيط تدفقات المستندات السريرية والإدارية.'],
'education'=>['Education','التعليم','fa-graduation-cap','Enable secure learning, administration and campus-wide print and IT services.','تمكين التعلم والإدارة وخدمات الطباعة وتكنولوجيا المعلومات الآمنة على مستوى المؤسسة التعليمية.'],
'retail'=>['Retail','التجزئة','fa-store','Connect stores, back offices and customer operations through dependable technology.','ربط الفروع والمكاتب الخلفية وعمليات العملاء من خلال تكنولوجيا موثوقة.'],
'logistics'=>['Logistics & Distribution','الخدمات اللوجستية والتوزيع','fa-truck','Keep distributed operations connected, documented and responsive.','الحفاظ على اتصال العمليات الموزعة وتوثيقها وسرعة استجابتها.'],
'oil-gas'=>['Oil & Gas','البترول والغاز','fa-oil-well','Support remote sites and critical operations with secure, resilient infrastructure.','دعم المواقع البعيدة والعمليات الحرجة ببنية تحتية آمنة ومرنة.']];
$d=$data[$slug]??['Industry Solutions','حلول القطاعات','fa-building','Technology aligned to your operational requirements.','تكنولوجيا متوافقة مع متطلباتك التشغيلية.']; ?>
<main><?php smt_breadcrumbs(); ?><section class="ui-page-hero industry-detail-hero"><div class="container"><i class="fa-solid <?php echo esc_attr($d[2]); ?> industry-hero-icon"></i><span class="eyebrow"><?php echo esc_html(smt_t('Industry expertise','خبرات القطاعات')); ?></span><h1><?php echo esc_html(smt_t($d[0],$d[1])); ?></h1><p><?php echo esc_html(smt_t($d[3],$d[4])); ?></p></div></section>
<section class="section"><div class="container"><div class="section-heading"><span class="section-kicker"><?php echo esc_html(smt_t('How we help','كيف نساعدك')); ?></span><h2><?php echo esc_html(smt_t('Integrated technology for sector-specific priorities','تكنولوجيا متكاملة لأولويات كل قطاع')); ?></h2></div><div class="ui-card-grid three"><article class="ui-card"><i class="fa-solid fa-print"></i><h3><?php echo esc_html(smt_t('Print & Document Control','التحكم في الطباعة والمستندات')); ?></h3><p><?php echo esc_html(smt_t('Reduce waste, improve governance and standardize document workflows.','تقليل الهدر وتحسين الحوكمة وتوحيد تدفقات المستندات.')); ?></p></article><article class="ui-card"><i class="fa-solid fa-server"></i><h3><?php echo esc_html(smt_t('Resilient Infrastructure','بنية تحتية مرنة')); ?></h3><p><?php echo esc_html(smt_t('Design secure, scalable platforms for critical business operations.','تصميم منصات آمنة وقابلة للتوسع للعمليات الحيوية.')); ?></p></article><article class="ui-card"><i class="fa-solid fa-headset"></i><h3><?php echo esc_html(smt_t('Managed Support','دعم مُدار')); ?></h3><p><?php echo esc_html(smt_t('Maintain service continuity through proactive support and clear SLAs.','الحفاظ على استمرارية الخدمة من خلال الدعم الاستباقي واتفاقيات مستوى الخدمة الواضحة.')); ?></p></article></div></div></section>
<section class="section section-alt"><div class="container final-cta"><div><span class="section-kicker"><?php echo esc_html(smt_t('Discuss your environment','ناقش بيئة عملك')); ?></span><h2><?php echo esc_html(smt_t('Build a practical technology roadmap for your organization.','ابنِ خارطة طريق تكنولوجية عملية لمؤسستك.')); ?></h2></div><a class="btn btn-primary" href="<?php echo esc_url(smt_page_url('contact')); ?>"><?php echo esc_html(smt_t('Book a Consultation','احجز استشارة')); ?></a></div></section></main><?php get_footer(); ?>
