<?php /* Template Name: Industries */ if (!defined('ABSPATH')) exit; get_header();
$industries = [
 ['fa-building-columns','Banking & Financial Services','Secure document workflows, resilient infrastructure, controlled printing, and productivity solutions for regulated environments.'],
 ['fa-landmark','Government','Reliable technology platforms that support public services, security, governance, and operational efficiency.'],
 ['fa-industry','Manufacturing','Print, infrastructure, automation, and support solutions designed for factories, plants, warehouses, and distributed operations.'],
 ['fa-heart-pulse','Healthcare','Secure information workflows, dependable printing, and infrastructure services that support clinical and administrative teams.'],
 ['fa-graduation-cap','Education','Cost-controlled printing, collaboration, cloud, and IT solutions for schools, universities, and training institutions.'],
 ['fa-store','Retail & Distribution','Scalable branch technology, document workflows, connectivity, and support for fast-moving multi-location operations.'],
 ['fa-truck-fast','Logistics','Reliable infrastructure, mobile workflows, secure documents, and managed services for supply-chain operations.'],
 ['fa-oil-well','Oil & Gas','Robust enterprise solutions for demanding sites, distributed teams, security requirements, and business continuity.'],
]; ?>
<main class="industries-page">
<section class="ui-page-hero"><div class="container"><span class="eyebrow">Sector-focused expertise</span><h1>Technology solutions built around your industry</h1><p>We combine cross-industry technology experience with a practical understanding of operational priorities, risk, cost, and service continuity.</p><div class="hero-actions"><a class="btn btn-gold" href="<?php echo esc_url(smt_page_url('contact')); ?>">Discuss Your Requirements</a><a class="btn btn-outline" href="#industry-grid">Explore Industries</a></div></div></section>
<section class="section" id="industry-grid"><div class="container"><?php smt_section_heading(['kicker'=>'Industries we serve','title'=>'Relevant solutions for complex operating environments','text'=>'Every engagement is tailored to the realities of your sector, locations, users, security requirements, and growth plans.','alignment'=>'center']); ?><div class="industry-detail-grid">
<?php foreach ($industries as $industry): ?><article class="industry-detail-card reveal"><div class="industry-detail-icon"><i class="fa-solid <?php echo esc_attr($industry[0]); ?>"></i></div><h2><?php echo esc_html($industry[1]); ?></h2><p><?php echo esc_html($industry[2]); ?></p><ul><li>Operational assessment</li><li>Right-sized solution design</li><li>Implementation and lifecycle support</li></ul><a href="<?php echo esc_url(smt_page_url('contact')); ?>">Talk to a sector specialist <i class="fa-solid fa-arrow-right"></i></a></article><?php endforeach; ?>
</div></div></section>
<section class="section ui-dark-section"><div class="container"><div class="industry-outcomes"><div><span class="section-kicker light">Business outcomes</span><h2>Technology aligned with operational priorities</h2><p>Our recommendations focus on measurable value across productivity, cost control, security, reliability, governance, and user experience.</p></div><div class="outcomes-grid"><span><i class="fa-solid fa-chart-line"></i>Higher productivity</span><span><i class="fa-solid fa-coins"></i>Lower lifecycle cost</span><span><i class="fa-solid fa-shield-halved"></i>Stronger security</span><span><i class="fa-solid fa-headset"></i>Reliable support</span></div></div></div></section>
<section class="ui-cta-section"><div class="container ui-cta-inner"><div><span class="section-kicker light">Start with an assessment</span><h2>Let us understand your environment and priorities.</h2><p>We will identify the most practical opportunities to simplify operations, improve reliability, and create more value.</p></div><div class="ui-cta-actions"><a class="btn btn-gold" href="<?php echo esc_url(smt_page_url('contact')); ?>">Request a Consultation</a></div></div></section>
</main><?php get_footer(); ?>
