<?php /* Template Name: Technology Assessment */
if (!defined('ABSPATH')) exit;
get_header();
?>
<main class="resource-detail-page assessment-page">
  <?php smt_breadcrumbs(); ?>
  <section class="ui-page-hero resource-detail-hero"><div class="container resource-detail-hero-grid"><div><span class="eyebrow"><?php echo esc_html(smt_t('Structured discovery','استكشاف منظم')); ?></span><h1><?php echo esc_html(smt_t('Start with a clear assessment of your technology environment.','ابدأ بتقييم واضح لبيئتك التقنية.')); ?></h1><p><?php echo esc_html(smt_t('A practical review helps identify cost, performance, security, workflow, and continuity opportunities before you commit to a solution.','تساعد المراجعة العملية على تحديد فرص التكلفة والأداء والأمان وسير العمل والاستمرارية قبل الالتزام بأي حل.')); ?></p><div class="hero-actions"><a class="btn btn-gold" href="<?php echo esc_url(smt_page_url('contact')); ?>"><?php echo esc_html(smt_t('Book an Assessment','احجز تقييمًا')); ?></a><a class="btn btn-outline" href="<?php echo esc_url(smt_page_url('fleet-savings-calculator')); ?>"><?php echo esc_html(smt_t('Try the Print Calculator','جرّب حاسبة الطباعة')); ?></a></div></div><aside class="resource-detail-symbol"><i class="fa-solid fa-clipboard-check"></i><strong><?php echo esc_html(smt_t('Evidence before investment','بيانات قبل الاستثمار')); ?></strong><span><?php echo esc_html(smt_t('Baseline • Gaps • Priorities • Roadmap','خط أساس • فجوات • أولويات • خارطة طريق')); ?></span></aside></div></section>

  <section class="section"><div class="container"><?php smt_section_heading(['kicker'=>smt_t('Assessment areas','مجالات التقييم'),'title'=>smt_t('Choose the scope that matches your priorities','اختر النطاق الذي يناسب أولوياتك'),'text'=>smt_t('Assess one area or combine multiple domains into a single improvement roadmap.','قيّم مجالًا واحدًا أو اجمع عدة مجالات في خارطة تحسين واحدة.'),'alignment'=>'center']); ?><div class="assessment-area-grid"><article><i class="fa-solid fa-print"></i><h2><?php echo esc_html(smt_t('Print & Documents','الطباعة والمستندات')); ?></h2><p><?php echo esc_html(smt_t('Fleet, volumes, contracts, cost, workflow, security, and support.','الأسطول والأحجام والعقود والتكلفة وسير العمل والأمان والدعم.')); ?></p></article><article><i class="fa-solid fa-server"></i><h2><?php echo esc_html(smt_t('Infrastructure','البنية التحتية')); ?></h2><p><?php echo esc_html(smt_t('Servers, storage, networks, endpoints, backup, and availability.','الخوادم والتخزين والشبكات والأجهزة والنسخ الاحتياطي والجاهزية.')); ?></p></article><article><i class="fa-solid fa-cloud"></i><h2><?php echo esc_html(smt_t('Cloud & Microsoft','السحابة ومايكروسوفت')); ?></h2><p><?php echo esc_html(smt_t('Licensing, identity, collaboration, security, migration, and governance.','التراخيص والهوية والتعاون والأمان والترحيل والحوكمة.')); ?></p></article><article><i class="fa-solid fa-shield-halved"></i><h2><?php echo esc_html(smt_t('Cybersecurity','الأمن السيبراني')); ?></h2><p><?php echo esc_html(smt_t('Risk, identity, devices, email, network, data, backup, and response.','المخاطر والهوية والأجهزة والبريد والشبكة والبيانات والنسخ والاستجابة.')); ?></p></article><article><i class="fa-solid fa-diagram-project"></i><h2><?php echo esc_html(smt_t('Workflow & Automation','سير العمل والأتمتة')); ?></h2><p><?php echo esc_html(smt_t('Documents, approvals, handoffs, bottlenecks, controls, and integrations.','المستندات والموافقات والتسليمات والاختناقات والضوابط والتكاملات.')); ?></p></article><article><i class="fa-solid fa-screwdriver-wrench"></i><h2><?php echo esc_html(smt_t('Support & Lifecycle','الدعم ودورة الحياة')); ?></h2><p><?php echo esc_html(smt_t('Assets, service levels, incidents, maintenance, cost, and renewal plans.','الأصول ومستويات الخدمة والحوادث والصيانة والتكلفة وخطط التجديد.')); ?></p></article></div></div></section>

  <section class="section ui-dark-section"><div class="container assessment-output-layout"><div><?php smt_section_heading(['kicker'=>smt_t('What you receive','ماذا تحصل عليه'),'title'=>smt_t('A practical baseline and prioritized next steps','خط أساس عملي وخطوات تالية مرتبة بالأولوية'),'text'=>smt_t('The assessment is designed to turn scattered information into a decision-ready view.','صُمم التقييم لتحويل المعلومات المتفرقة إلى رؤية جاهزة لاتخاذ القرار.'),'theme'=>'dark']); ?></div><ol class="assessment-output-list"><li><span>01</span><strong><?php echo esc_html(smt_t('Current-state summary','ملخص الوضع الحالي')); ?></strong></li><li><span>02</span><strong><?php echo esc_html(smt_t('Key risks and improvement gaps','أهم المخاطر وفجوات التحسين')); ?></strong></li><li><span>03</span><strong><?php echo esc_html(smt_t('Prioritized recommendations','توصيات مرتبة حسب الأولوية')); ?></strong></li><li><span>04</span><strong><?php echo esc_html(smt_t('Implementation roadmap','خارطة طريق للتنفيذ')); ?></strong></li></ol></div></section>

  <section class="ui-cta-section"><div class="container ui-cta-inner"><div><span class="section-kicker light"><?php echo esc_html(smt_t('Build the right baseline','ابنِ خط الأساس الصحيح')); ?></span><h2><?php echo esc_html(smt_t('Book a focused assessment with our solutions team.','احجز تقييمًا مركزًا مع فريق الحلول.')); ?></h2></div><div class="ui-cta-actions"><a class="btn btn-gold" href="<?php echo esc_url(smt_page_url('contact')); ?>"><?php echo esc_html(smt_t('Request an Assessment','اطلب تقييمًا')); ?></a></div></div></section>
</main>
<?php get_footer(); ?>
