<?php /* Template Name: Resources */
if (!defined('ABSPATH')) exit;
get_header();
$resources = smt_resource_catalog();
?>
<main class="resources-hub-page">
  <section class="ui-page-hero resources-hub-hero smt-photo-hero"><div class="container resources-hero-grid"><div class="smt-photo-hero-copy"><h1><?php echo esc_html(smt_t('Resources that help you make better technology decisions.','موارد تساعدك على اتخاذ قرارات تقنية أفضل.')); ?></h1><p><?php echo esc_html(smt_t('Use our calculators, assessments, guides, company materials, insights, and expert support to evaluate opportunities and plan your next improvement initiative.','استخدم الحاسبات والتقييمات والأدلة ومواد الشركة والرؤى ودعم الخبراء لتقييم الفرص والتخطيط لمبادرة التحسين التالية.')); ?></p></div><div class="smt-photo-panel resources-hero-photo"><?php smt_visual_picture('resources_hero', smt_t('Technology consultant helping a customer evaluate business options','مستشار تقني يساعد عميلًا على تقييم الخيارات المناسبة للأعمال'), ['loading'=>'eager','fetchpriority'=>'high','class'=>'smt-visual-image']); ?><div class="smt-photo-caption"><i class="fa-solid fa-compass"></i><span><strong><?php echo esc_html(smt_t('Start with the right question','ابدأ بالسؤال الصحيح')); ?></strong><small><?php echo esc_html(smt_t('Cost • Capability • Risk • Roadmap','التكلفة • القدرة • المخاطر • خارطة الطريق')); ?></small></span></div></div></div></section>

  <section class="section"><div class="container"><?php smt_section_heading(['kicker'=>smt_t('Resource center','مركز الموارد'),'title'=>smt_t('Choose the right starting point','اختر نقطة البداية المناسبة'),'text'=>smt_t('Explore the resources below or speak with our consultants for guidance tailored to your organization.','استكشف الموارد التالية أو تحدث مع مستشارينا للحصول على توجيه يناسب مؤسستك.'),'alignment'=>'center']); ?><div class="resource-hub-grid">
    <?php foreach($resources as $slug=>$resource): ?><article class="resource-hub-card reveal"><div class="resource-hub-icon"><i class="fa-solid <?php echo esc_attr($resource['icon']); ?>"></i></div><h2><?php echo esc_html($resource['title']); ?></h2><p><?php echo esc_html($resource['text']); ?></p><a href="<?php echo esc_url(smt_page_url($slug)); ?>"><?php echo esc_html($resource['cta']); ?> <i class="fa-solid fa-arrow-right"></i></a></article><?php endforeach; ?>
  </div></div></section>

  <section class="section ui-surface-section"><div class="container resource-spotlight-layout"><div><span class="section-kicker"><?php echo esc_html(smt_t('Featured tool','أداة مميزة')); ?></span><h2><?php echo esc_html(smt_t('Turn print-cost assumptions into a measurable opportunity.','حوّل افتراضات تكلفة الطباعة إلى فرصة يمكن قياسها.')); ?></h2><p><?php echo esc_html(smt_t('The Fleet Savings Calculator creates an immediate high-level estimate, then helps you move toward a verified professional assessment.','تقدم حاسبة وفر الطباعة تقديرًا مبدئيًا فوريًا، ثم تساعدك على الانتقال إلى تقييم احترافي موثق.')); ?></p><a class="btn btn-primary" href="<?php echo esc_url(smt_page_url('fleet-savings-calculator')); ?>"><?php echo esc_html(smt_t('Use the Calculator','استخدم الحاسبة')); ?></a></div><aside class="resource-score-card"><div><span><?php echo esc_html(smt_t('Current environment','الوضع الحالي')); ?></span><strong><?php echo esc_html(smt_t('Cost visibility','وضوح التكلفة')); ?></strong></div><div class="resource-score-bars"><i></i><i></i><i></i><i></i><i></i></div><small><?php echo esc_html(smt_t('Move from assumptions to fact-based planning.','انتقل من الافتراضات إلى تخطيط قائم على البيانات.')); ?></small></aside></div></section>

  <section class="ui-cta-section"><div class="container ui-cta-inner"><div><span class="section-kicker light"><?php echo esc_html(smt_t('Need specific information?','تحتاج إلى معلومة محددة؟')); ?></span><h2><?php echo esc_html(smt_t('Speak with a Source More consultant.','تحدث مع مستشار من سورس مور.')); ?></h2><p><?php echo esc_html(smt_t('Tell us what you are evaluating, and we will direct you to the right solution, resource, or next step.','أخبرنا بما تقوم بتقييمه وسنوجهك إلى الحل أو المورد أو الخطوة التالية المناسبة.')); ?></p></div><div class="ui-cta-actions"><a class="btn btn-gold" href="<?php echo esc_url(smt_page_url('contact')); ?>"><?php echo esc_html(smt_t('Contact Our Experts','تواصل مع خبرائنا')); ?></a></div></div></section>
</main>
<?php get_footer(); ?>
