<?php /* Template Name: Company Profile */
if (!defined('ABSPATH')) exit;
get_header();
$profile_url = smt_get_setting('profile_url');
?>
<main class="resource-detail-page company-profile-page">
  <?php smt_breadcrumbs(); ?>
  <section class="ui-page-hero resource-detail-hero"><div class="container resource-detail-hero-grid"><div><span class="eyebrow"><?php echo esc_html(smt_t('Source More','سورس مور')); ?></span><h1><?php echo esc_html(smt_t('One source for integrated business technology.','مصدر واحد لتكنولوجيا الأعمال المتكاملة.')); ?></h1><p><?php echo esc_html(smt_t('Explore our company positioning, solution portfolio, delivery approach, sector coverage, and the value we create for organizations.','تعرّف على مكانة الشركة ومحفظة الحلول ومنهجية التنفيذ والقطاعات والقيمة التي نصنعها للمؤسسات.')); ?></p><div class="hero-actions"><?php if($profile_url): ?><a class="btn btn-gold" href="<?php echo esc_url($profile_url); ?>" target="_blank" rel="noopener"><?php echo esc_html(smt_t('Download Company Profile','حمّل الملف التعريفي')); ?></a><?php else: ?><a class="btn btn-gold" href="<?php echo esc_url(smt_page_url('contact')); ?>"><?php echo esc_html(smt_t('Request Company Profile','اطلب الملف التعريفي')); ?></a><?php endif; ?><a class="btn btn-outline" href="<?php echo esc_url(smt_page_url('about-us')); ?>"><?php echo esc_html(smt_t('Learn About Us','تعرّف علينا')); ?></a></div></div><aside class="resource-detail-symbol"><i class="fa-solid fa-file-pdf"></i><strong><?php echo esc_html(smt_t('Corporate overview','نظرة مؤسسية')); ?></strong><span><?php echo esc_html(smt_t('Capabilities • Delivery • Sectors • Value','القدرات • التنفيذ • القطاعات • القيمة')); ?></span></aside></div></section>

  <section class="section"><div class="container"><?php smt_section_heading(['kicker'=>smt_t('What you will find','ماذا ستجد'),'title'=>smt_t('A clear view of who we are and how we deliver','رؤية واضحة لمن نحن وكيف ننفذ'),'text'=>smt_t('The company profile is designed for customers, partners, vendors, and stakeholders evaluating Source More.','صُمم الملف التعريفي للعملاء والشركاء والموردين وأصحاب المصلحة الراغبين في تقييم سورس مور.'),'alignment'=>'center']); ?><div class="profile-topic-grid"><article><i class="fa-solid fa-building"></i><h2><?php echo esc_html(smt_t('Company Overview','نبذة عن الشركة')); ?></h2><p><?php echo esc_html(smt_t('Our purpose, positioning, operating model, and value proposition.','هدفنا ومكانتنا ونموذج عملنا والقيمة التي نقدمها.')); ?></p></article><article><i class="fa-solid fa-layer-group"></i><h2><?php echo esc_html(smt_t('Solution Portfolio','محفظة الحلول')); ?></h2><p><?php echo esc_html(smt_t('Print, documents, infrastructure, cloud, cybersecurity, software, and support.','الطباعة والمستندات والبنية التحتية والسحابة والأمن والبرمجيات والدعم.')); ?></p></article><article><i class="fa-solid fa-route"></i><h2><?php echo esc_html(smt_t('Delivery Approach','منهجية التنفيذ')); ?></h2><p><?php echo esc_html(smt_t('Assessment, design, implementation, support, and continuous improvement.','التقييم والتصميم والتنفيذ والدعم والتحسين المستمر.')); ?></p></article><article><i class="fa-solid fa-briefcase"></i><h2><?php echo esc_html(smt_t('Industries & Use Cases','القطاعات وحالات الاستخدام')); ?></h2><p><?php echo esc_html(smt_t('Sector priorities and practical business applications.','أولويات القطاعات والتطبيقات العملية للأعمال.')); ?></p></article></div></div></section>

  <section class="section ui-surface-section"><div class="container profile-value-layout"><div><?php smt_section_heading(['kicker'=>smt_t('Our value proposition','عرض القيمة'),'title'=>smt_t('We connect technology decisions to business outcomes.','نربط القرارات التقنية بنتائج الأعمال.'),'text'=>smt_t('Source More brings multiple technology domains together under one accountable engagement model.','تجمع سورس مور مجالات تقنية متعددة تحت نموذج تعاون واحد بمسؤولية واضحة.')]); ?></div><div class="profile-value-list"><span><i class="fa-solid fa-circle-check"></i><?php echo esc_html(smt_t('One accountable technology partner','شريك تقني واحد بمسؤولية واضحة')); ?></span><span><i class="fa-solid fa-circle-check"></i><?php echo esc_html(smt_t('Solutions designed around operational priorities','حلول مصممة حول أولويات التشغيل')); ?></span><span><i class="fa-solid fa-circle-check"></i><?php echo esc_html(smt_t('Lifecycle cost and service visibility','وضوح تكلفة دورة الحياة والخدمة')); ?></span><span><i class="fa-solid fa-circle-check"></i><?php echo esc_html(smt_t('Scalable roadmap for future growth','خارطة طريق قابلة للتوسع مع النمو')); ?></span></div></div></section>

  <section class="ui-cta-section"><div class="container ui-cta-inner"><div><span class="section-kicker light"><?php echo esc_html(smt_t('Continue the conversation','أكمل الحوار')); ?></span><h2><?php echo esc_html(smt_t('Discuss how Source More can support your organization.','ناقش كيف يمكن لسورس مور دعم مؤسستك.')); ?></h2></div><div class="ui-cta-actions"><a class="btn btn-gold" href="<?php echo esc_url(smt_page_url('contact')); ?>"><?php echo esc_html(smt_t('Book a Consultation','احجز استشارة')); ?></a></div></div></section>
</main>
<?php get_footer(); ?>
