<?php /* Template Name: Our Services */ get_header(); $catalog=smt_solution_catalog(); ?>
<main class="solutions-hub-page">
<section class="ui-page-hero solutions-hub-hero"><div class="container"><span class="eyebrow">Source More Technology</span><h1>Enterprise Technology Solutions</h1><p>One partner for print, documents, infrastructure, cloud, cybersecurity, automation, and lifecycle support.</p><div class="hero-actions"><a class="btn btn-gold" href="<?php echo esc_url(smt_page_url('contact')); ?>">Request Consultation</a><a class="btn btn-outline" href="#solutions-grid">Explore Solutions</a></div></div></section>
<section class="section"><div class="container solution-intro-grid"><div><?php smt_section_heading(array('kicker'=>'Technology that creates business value','title'=>'Solutions designed around outcomes—not product lists','text'=>'We help organizations improve productivity, control operating costs, strengthen security, and build reliable technology environments. Every engagement begins with understanding the business challenge and defining measurable results.')); ?></div><aside class="solution-consult-card"><i class="fa-solid fa-compass"></i><h3>Not sure where to start?</h3><p>Our consultants can assess your current environment and identify the highest-value opportunities.</p><a href="<?php echo esc_url(smt_page_url('contact')); ?>">Book an assessment <i class="fa-solid fa-arrow-right"></i></a></aside></div></section>
<section class="section ui-surface-section" id="solutions-grid"><div class="container"><?php smt_section_heading(array('kicker'=>'Our portfolio','title'=>'Integrated solutions for modern organizations','text'=>'Choose a focused service or combine multiple capabilities through one accountable technology partner.','alignment'=>'center')); ?><div class="solutions-premium-grid">
<?php foreach($catalog as $slug=>$s): ?><article class="solution-premium-card reveal"><div class="solution-premium-icon"><i class="fa-solid <?php echo esc_attr($s['icon']); ?>"></i></div><h2><?php echo esc_html($s['title']); ?></h2><p><?php echo esc_html($s['intro']); ?></p><ul><?php foreach(array_slice($s['features'],0,4) as $f): ?><li><i class="fa-solid fa-check"></i><?php echo esc_html($f); ?></li><?php endforeach; ?></ul><a href="<?php echo esc_url(smt_page_url($slug)); ?>">Explore solution <i class="fa-solid fa-arrow-right"></i></a></article><?php endforeach; ?>
</div></div></section>
<section class="section"><div class="container"><?php smt_section_heading(array('kicker'=>'Why Source More Technology','title'=>'A different kind of technology partner','alignment'=>'center')); ?><div class="vendor-comparison"><div class="comparison-column traditional"><h3>Traditional supplier</h3><ul><li>Sells individual products</li><li>Reactive service model</li><li>Limited visibility across vendors</li><li>Focuses on initial purchase price</li><li>Ends at project handover</li></ul></div><div class="comparison-column source-more"><span class="comparison-badge">Our approach</span><h3>Source More Technology</h3><ul><li>Solves business and operational problems</li><li>Proactive support and optimization</li><li>One accountable technology partner</li><li>Focuses on total lifecycle value</li><li>Builds long-term measurable partnerships</li></ul></div></div></div></section>
<section class="section ui-dark-section"><div class="container"><?php smt_section_heading(array('kicker'=>'How we deliver','title'=>'A structured methodology that reduces risk','text'=>'Clear stages, accountable ownership, and continuous optimization from discovery through support.','alignment'=>'center','theme'=>'dark')); ?><ol class="ui-process-grid solutions-five-step"><li><span>01</span><h3>Assess</h3><p>Current environment, requirements, risks, and costs.</p></li><li><span>02</span><h3>Design</h3><p>Right-sized technical and commercial solution.</p></li><li><span>03</span><h3>Implement</h3><p>Controlled deployment, testing, and handover.</p></li><li><span>04</span><h3>Support</h3><p>Service levels, monitoring, and escalation.</p></li><li><span>05</span><h3>Optimize</h3><p>Reporting, improvement, and lifecycle planning.</p></li></ol></div></section>
<section class="ui-cta-section"><div class="container ui-cta-inner"><div><span class="section-kicker light">Modernize with confidence</span><h2>Ready to build a more efficient technology environment?</h2><p>Tell us what you are trying to improve. We will help define the most practical path forward.</p></div><div class="ui-cta-actions"><a class="btn btn-gold" href="<?php echo esc_url(smt_page_url('contact')); ?>">Contact Our Experts</a></div></div></section>
</main><?php get_footer(); ?>
