<?php /* Template Name: Contact Source More */ if (!defined('ABSPATH')) exit; get_header();
$phone = smt_get_setting('phone') ?: '+20 100 000 0000';
$email = smt_get_setting('email') ?: 'info@sourcemoreg.com';
$address = smt_t(smt_get_setting('address_en'), smt_get_setting('address_ar')) ?: smt_t('Cairo, Egypt','القاهرة، مصر');
$whatsapp = preg_replace('/\D+/', '', smt_get_setting('whatsapp') ?: $phone);
?>
<main class="contact-page">
<?php smt_breadcrumbs(); ?>
<section class="ui-page-hero contact-hero smt-photo-hero"><div class="container smt-photo-hero-grid"><div class="smt-photo-hero-copy"><h1><?php echo esc_html(smt_t('How can we help your organization?','كيف يمكننا مساعدة مؤسستك؟')); ?></h1><p><?php echo esc_html(smt_t('Tell us about your requirements, current challenges, or upcoming project. Our team will help define the most practical next step.','أخبرنا باحتياجاتك أو التحديات الحالية أو مشروعك القادم، وسيساعدك فريقنا في تحديد الخطوة العملية التالية.')); ?></p><div class="contact-hero-proof"><span><i class="fa-solid fa-circle-check"></i><?php echo esc_html(smt_t('Practical recommendations','توصيات عملية')); ?></span><span><i class="fa-solid fa-circle-check"></i><?php echo esc_html(smt_t('Clear next steps','خطوات تالية واضحة')); ?></span></div></div><div class="smt-photo-panel contact-hero-photo"><?php smt_visual_picture('contact_hero', smt_t('Source More consultant discussing business requirements with a customer','مستشار من سورس مور يناقش احتياجات العمل مع أحد العملاء'), ['loading'=>'eager','fetchpriority'=>'high','class'=>'smt-visual-image']); ?><div class="smt-photo-caption"><i class="fa-solid fa-comments"></i><span><strong><?php echo esc_html(smt_t('Talk to a solutions consultant','تحدث مع مستشار حلول')); ?></strong><small><?php echo esc_html(smt_t('Print, IT, cloud, security and digital transformation','الطباعة وتكنولوجيا المعلومات والسحابة والأمن والتحول الرقمي')); ?></small></span></div></div></div></section>
<section class="section"><div class="container contact-layout"><div class="contact-information"><span class="section-kicker"><?php echo esc_html(smt_t('Contact Source More','تواصل مع سورس مور')); ?></span><h2><?php echo esc_html(smt_t('Talk to our solutions team','تحدث مع فريق الحلول')); ?></h2><p><?php echo esc_html(smt_t('Contact us for consultations, fleet assessments, solution design, quotations, demonstrations, maintenance, or technical support.','تواصل معنا للاستشارات وتقييم أساطيل الطباعة وتصميم الحلول وعروض الأسعار والعروض التوضيحية والصيانة والدعم الفني.')); ?></p><div class="contact-methods">
<a href="tel:<?php echo esc_attr(preg_replace('/[^+0-9]/','',$phone)); ?>"><i class="fa-solid fa-phone"></i><span><small><?php echo esc_html(smt_t('Phone','الهاتف')); ?></small><strong><?php echo esc_html($phone); ?></strong></span></a>
<a href="https://wa.me/<?php echo esc_attr($whatsapp); ?>?text=<?php echo rawurlencode(smt_t('Hello Source More, I would like to discuss a business requirement.','مرحبًا سورس مور، أود مناقشة أحد احتياجات العمل.')); ?>" target="_blank" rel="noopener"><i class="fa-brands fa-whatsapp"></i><span><small>WhatsApp</small><strong><?php echo esc_html(smt_t('Start a conversation','ابدأ محادثة')); ?></strong></span></a>
<a href="mailto:<?php echo esc_attr($email); ?>"><i class="fa-solid fa-envelope"></i><span><small><?php echo esc_html(smt_t('Email','البريد الإلكتروني')); ?></small><strong><?php echo esc_html($email); ?></strong></span></a>
<div><i class="fa-solid fa-location-dot"></i><span><small><?php echo esc_html(smt_t('Location','الموقع')); ?></small><strong><?php echo esc_html($address); ?></strong></span></div>
</div></div>
<div class="contact-form-card"><span class="section-kicker"><?php echo esc_html(smt_t('Request a consultation','اطلب استشارة')); ?></span><h2><?php echo esc_html(smt_t('Tell us what you need','أخبرنا بما تحتاج إليه')); ?></h2><?php while(have_posts()): the_post(); if(trim(get_the_content())): the_content(); else: ?><form class="smt-contact-form" id="smt-contact-form" novalidate><div class="form-grid">
<label><?php echo esc_html(smt_t('Full name','الاسم الكامل')); ?> *<input type="text" name="name" required autocomplete="name"></label><label><?php echo esc_html(smt_t('Company','الشركة')); ?><input type="text" name="company" autocomplete="organization"></label>
<label><?php echo esc_html(smt_t('Business email','البريد الإلكتروني للعمل')); ?> *<input type="email" name="email" required autocomplete="email"></label><label><?php echo esc_html(smt_t('Phone number','رقم الهاتف')); ?><input type="tel" name="phone" autocomplete="tel"></label>
<label class="full"><?php echo esc_html(smt_t('Area of interest','مجال الاهتمام')); ?><select name="interest"><option>Managed Print Services</option><option>Enterprise Printing</option><option>Document Management</option><option>IT Infrastructure</option><option>Cloud & Microsoft Solutions</option><option>Cybersecurity</option><option>Office Automation</option><option>Maintenance & Support</option><option>Other</option></select></label>
<label class="full"><?php echo esc_html(smt_t('How can we help?','كيف يمكننا مساعدتك؟')); ?> *<textarea name="message" rows="5" required></textarea></label>
<label class="smt-honeypot" aria-hidden="true">Website<input type="text" name="website" tabindex="-1" autocomplete="off"></label>
<label class="full consent-field"><input type="checkbox" name="consent" value="1" required> <span><?php echo esc_html(smt_t('I agree that Source More may use my information to respond to this inquiry.','أوافق على استخدام سورس مور لبياناتي للرد على هذا الاستفسار.')); ?></span></label>
</div><button class="btn btn-primary" type="submit"><?php echo esc_html(smt_t('Send Inquiry','إرسال الاستفسار')); ?></button><div class="form-status" role="status" aria-live="polite"></div></form><?php endif; endwhile; ?></div></div></section>
</main><?php get_footer(); ?>
