<?php /* Template Name: Our Services */
if (!defined('ABSPATH')) exit;
get_header(); $catalog=smt_solution_catalog(); ?>
<main class="solutions-hub-page">
<section class="ui-page-hero solutions-hub-hero smt-photo-hero"><div class="container smt-photo-hero-grid"><div class="smt-photo-hero-copy"><h1><?php echo esc_html(smt_t('Enterprise Technology Solutions','حلول تقنية متكاملة تدفع أعمالك للأمام')); ?></h1><p><?php echo esc_html(smt_t('One accountable partner for print, documents, infrastructure, cloud, cybersecurity, automation, and lifecycle support.','شريك واحد مسؤول يجمع حلول الطباعة والمستندات والبنية التحتية والسحابة والأمن السيبراني والأتمتة والدعم المستمر.')); ?></p><div class="hero-actions"><a class="btn btn-gold" href="<?php echo esc_url(smt_page_url('contact')); ?>"><?php echo esc_html(smt_t('Request Consultation','اطلب استشارة')); ?></a><a class="btn btn-outline" href="#solutions-grid"><?php echo esc_html(smt_t('Explore Solutions','استكشف الحلول')); ?></a></div></div><div class="smt-photo-panel smt-photo-hero-media"><?php smt_visual_picture('solutions_hero', smt_t('Integrated enterprise technology covering print, cloud, infrastructure, security and automation','تكنولوجيا مؤسسية متكاملة تشمل الطباعة والسحابة والبنية التحتية والأمن والأتمتة'), ['loading'=>'eager','fetchpriority'=>'high','class'=>'smt-visual-image']); ?><div class="smt-photo-badge"><i class="fa-solid fa-layer-group"></i><span><strong><?php echo esc_html(smt_t('One integrated portfolio','محفظة حلول متكاملة')); ?></strong><small><?php echo esc_html(smt_t('Designed around business outcomes','مصممة حول نتائج الأعمال')); ?></small></span></div></div></div></section>
<section class="section"><div class="container solution-intro-grid"><div><?php smt_section_heading(array(
  'kicker'=>smt_t('Technology that creates business value','تكنولوجيا تصنع قيمة للأعمال'),
  'title'=>smt_t('Solutions designed around outcomes—not product lists','نصمم الحل حول النتيجة التي تريدها، لا حول قائمة منتجات'),
  'text'=>smt_t('We help organizations improve productivity, control operating costs, strengthen security, and build reliable technology environments. Every engagement starts by understanding the business challenge and defining measurable results.','نساعد المؤسسات على رفع الإنتاجية، وضبط تكاليف التشغيل، وتعزيز الأمان، وبناء بيئة تقنية يمكن الاعتماد عليها. نبدأ دائمًا بفهم التحدي وتحديد النتيجة التي يمكن قياسها.')
)); ?></div><aside class="solution-consult-card"><i class="fa-solid fa-compass"></i><h3><?php echo esc_html(smt_t('Not sure where to start?','لست متأكدًا من نقطة البداية؟')); ?></h3><p><?php echo esc_html(smt_t('Our consultants can assess your current environment and identify the highest-value opportunities.','يستطيع فريقنا تقييم بيئة العمل الحالية وتحديد فرص التحسين الأعلى تأثيرًا وقيمة.')); ?></p><a href="<?php echo esc_url(smt_page_url('contact')); ?>"><?php echo esc_html(smt_t('Book an assessment','احجز تقييمًا مبدئيًا')); ?> <i class="fa-solid fa-arrow-right"></i></a></aside></div></section>
<section class="section ui-surface-section" id="solutions-grid"><div class="container"><?php smt_section_heading(array(
  'kicker'=>smt_t('Our portfolio','محفظة الحلول'),
  'title'=>smt_t('Integrated capabilities for modern organizations','قدرات متكاملة لمؤسسات تبحث عن أداء أقوى'),
  'text'=>smt_t('Choose a focused service or combine multiple capabilities through one accountable technology partner.','اختر خدمة محددة أو اجمع أكثر من قدرة ضمن منظومة واحدة يديرها شريك تقني مسؤول.'),
  'alignment'=>'center'
)); ?><div class="solutions-premium-grid">
<?php foreach($catalog as $slug=>$s): ?><article class="solution-premium-card reveal"><div class="solution-premium-icon"><i class="fa-solid <?php echo esc_attr($s['icon']); ?>"></i></div><h2><?php echo esc_html($s['title']); ?></h2><p><?php echo esc_html($s['intro']); ?></p><ul><?php foreach(array_slice($s['features'],0,4) as $f): ?><li><i class="fa-solid fa-check"></i><?php echo esc_html($f); ?></li><?php endforeach; ?></ul><a href="<?php echo esc_url(smt_page_url($slug)); ?>"><?php echo esc_html(smt_t('Explore solution','اكتشف الحل')); ?> <i class="fa-solid fa-arrow-right"></i></a></article><?php endforeach; ?>
</div></div></section>
<section class="section"><div class="container"><?php smt_section_heading(array('kicker'=>smt_t('Why Source More','لماذا سورس مور؟'),'title'=>smt_t('A different kind of technology partner','شريك يفهم أهداف العمل قبل أن يقترح التكنولوجيا'),'alignment'=>'center')); ?><div class="vendor-comparison"><div class="comparison-column traditional"><h3><?php echo esc_html(smt_t('Traditional supplier','المورد التقليدي')); ?></h3><ul><li><?php echo esc_html(smt_t('Sells individual products','يبيع منتجات منفصلة')); ?></li><li><?php echo esc_html(smt_t('Reactive service model','يتحرك بعد ظهور المشكلة')); ?></li><li><?php echo esc_html(smt_t('Limited visibility across vendors','رؤية محدودة مع تعدد الموردين')); ?></li><li><?php echo esc_html(smt_t('Focuses on initial purchase price','يركز على سعر الشراء فقط')); ?></li><li><?php echo esc_html(smt_t('Ends at project handover','ينتهي دوره عند التسليم')); ?></li></ul></div><div class="comparison-column source-more"><span class="comparison-badge"><?php echo esc_html(smt_t('Our approach','منهجنا')); ?></span><h3><?php echo esc_html(smt_t('Source More','سورس مور')); ?></h3><ul><li><?php echo esc_html(smt_t('Solves business and operational problems','يحل تحديات الأعمال والتشغيل')); ?></li><li><?php echo esc_html(smt_t('Proactive support and optimization','دعم استباقي وتحسين مستمر')); ?></li><li><?php echo esc_html(smt_t('One accountable technology partner','شريك تقني واحد ومسؤول')); ?></li><li><?php echo esc_html(smt_t('Focuses on total lifecycle value','يركز على القيمة طوال دورة الحياة')); ?></li><li><?php echo esc_html(smt_t('Builds long-term measurable partnerships','يبني شراكة طويلة الأجل بنتائج قابلة للقياس')); ?></li></ul></div></div></div></section>
<section class="section ui-dark-section"><div class="container"><?php smt_section_heading(array('kicker'=>smt_t('How we deliver','كيف ننفذ'),'title'=>smt_t('A structured methodology that reduces risk','منهجية واضحة تقلل المخاطر وتحافظ على استمرارية الأعمال'),'text'=>smt_t('Clear stages, accountable ownership, and continuous optimization from discovery through support.','مراحل محددة ومسؤوليات واضحة وتحسين مستمر من التقييم وحتى الدعم.'),'alignment'=>'center','theme'=>'dark')); ?><ol class="ui-process-grid solutions-five-step"><li><span>01</span><h3><?php echo esc_html(smt_t('Assess','نقيّم')); ?></h3><p><?php echo esc_html(smt_t('Current environment, requirements, risks, and costs.','البيئة الحالية والاحتياجات والمخاطر والتكلفة.')); ?></p></li><li><span>02</span><h3><?php echo esc_html(smt_t('Design','نصمم')); ?></h3><p><?php echo esc_html(smt_t('Right-sized technical and commercial solution.','حل فني وتجاري مناسب للحجم والأهداف.')); ?></p></li><li><span>03</span><h3><?php echo esc_html(smt_t('Implement','ننفذ')); ?></h3><p><?php echo esc_html(smt_t('Controlled deployment, testing, and handover.','تنفيذ منظم واختبارات وتسليم واضح.')); ?></p></li><li><span>04</span><h3><?php echo esc_html(smt_t('Support','ندعم')); ?></h3><p><?php echo esc_html(smt_t('Service levels, monitoring, and escalation.','مستويات خدمة ومراقبة وتصعيد منظم.')); ?></p></li><li><span>05</span><h3><?php echo esc_html(smt_t('Optimize','نطوّر')); ?></h3><p><?php echo esc_html(smt_t('Reporting, improvement, and lifecycle planning.','تقارير وتحسين وتخطيط لدورة الحياة.')); ?></p></li></ol></div></section>
<section class="ui-cta-section"><div class="container ui-cta-inner"><div><span class="section-kicker light"><?php echo esc_html(smt_t('Modernize with confidence','تطوّر بثقة')); ?></span><h2><?php echo esc_html(smt_t('Ready to build a more efficient technology environment?','جاهز لبناء بيئة تقنية أكثر كفاءة وأمانًا؟')); ?></h2><p><?php echo esc_html(smt_t('Tell us what you want to improve. We will help define the most practical path forward.','شاركنا ما تريد تحسينه، وسنساعدك على تحديد المسار العملي الأنسب.')); ?></p></div><div class="ui-cta-actions"><a class="btn btn-gold" href="<?php echo esc_url(smt_page_url('contact')); ?>"><?php echo esc_html(smt_t('Contact Our Experts','تواصل مع خبرائنا')); ?></a></div></div></section>
</main><?php get_footer(); ?>
