<?php /* Template Name: FAQs and Support */
if (!defined('ABSPATH')) exit;
get_header();
$faqs = [
  [smt_t('What solutions does Source More provide?','ما الحلول التي تقدمها سورس مور؟'),smt_t('We provide managed print, enterprise printing, document management, office automation, IT infrastructure, cloud and Microsoft, cybersecurity, maintenance, consulting, and integrated digital solutions.','نقدم خدمات الطباعة المُدارة وحلول الطباعة المؤسسية وإدارة المستندات وأتمتة بيئة العمل والبنية التحتية والسحابة ومايكروسوفت والأمن السيبراني والصيانة والاستشارات والحلول الرقمية المتكاملة.')],
  [smt_t('Do you sell products or only provide services?','هل تبيعون منتجات أم تقدمون خدمات فقط؟'),smt_t('We provide both products and services. The final recommendation can include hardware, software, subscriptions, implementation, support, and managed-service components.','نوفر المنتجات والخدمات معًا. وقد تشمل التوصية النهائية أجهزة وبرمجيات واشتراكات وتنفيذًا ودعمًا ومكونات خدمة مُدارة.')],
  [smt_t('How does an engagement normally begin?','كيف يبدأ التعاون عادةً؟'),smt_t('Most engagements begin with a discovery call or assessment. We review the current environment, priorities, constraints, and desired outcomes before proposing the next step.','يبدأ معظم التعاون بمكالمة استكشافية أو تقييم. نراجع الوضع الحالي والأولويات والقيود والنتائج المطلوبة قبل اقتراح الخطوة التالية.')],
  [smt_t('Can you support multiple branches or locations?','هل يمكنكم دعم فروع أو مواقع متعددة؟'),smt_t('Yes. We design centralized standards, monitoring, support, reporting, and governance for distributed organizations and multi-site operations.','نعم. نصمم معايير مركزية ومراقبة ودعمًا وتقارير وحوكمة للمؤسسات الموزعة والعمليات متعددة المواقع.')],
  [smt_t('Do you offer annual maintenance and managed support?','هل تقدمون عقود صيانة سنوية ودعمًا مُدارًا؟'),smt_t('Yes. Support can include preventive and corrective maintenance, help desk, remote monitoring, SLAs, reporting, spare-parts options, and lifecycle planning.','نعم. قد يشمل الدعم الصيانة الوقائية والتصحيحية ومكتب المساعدة والمراقبة عن بُعد ومستويات الخدمة والتقارير وخيارات قطع الغيار وتخطيط دورة الحياة.')],
  [smt_t('Can you help reduce printing costs?','هل يمكنكم المساعدة في خفض تكاليف الطباعة؟'),smt_t('Yes. We assess devices, volumes, contracts, consumables, service costs, utilization, security, and workflows to identify verified optimization opportunities.','نعم. نقيم الأجهزة والأحجام والعقود والمستهلكات وتكاليف الخدمة والاستخدام والأمان وسير العمل لتحديد فرص تحسين موثقة.')],
  [smt_t('How do I request technical support?','كيف أطلب دعمًا فنيًا؟'),smt_t('Use the Contact page and select maintenance or technical support, or contact the phone, email, or WhatsApp details shown in the footer.','استخدم صفحة تواصل معنا واختر الصيانة أو الدعم الفني، أو تواصل عبر الهاتف أو البريد أو واتساب الموضحة في الفوتر.')],
  [smt_t('How quickly will your team respond?','ما المدة المتوقعة لرد الفريق؟'),smt_t('Response time depends on the request type and any active service agreement. New business inquiries are reviewed by the solutions team, while contracted support follows the agreed SLA.','يعتمد زمن الاستجابة على نوع الطلب واتفاقية الخدمة القائمة. يراجع فريق الحلول الاستفسارات الجديدة، بينما يخضع الدعم المتعاقد عليه لمستوى الخدمة المتفق عليه.')],
];
?>
<main class="resource-detail-page faq-support-page">
  <?php smt_breadcrumbs(); ?>
  <section class="ui-page-hero resource-detail-hero"><div class="container resource-detail-hero-grid"><div><span class="eyebrow"><?php echo esc_html(smt_t('Answers & assistance','إجابات ومساعدة')); ?></span><h1><?php echo esc_html(smt_t('Clear answers. The right support path.','إجابات واضحة. ومسار الدعم المناسب.')); ?></h1><p><?php echo esc_html(smt_t('Find answers to common questions about our solutions, engagement model, implementation, and support services.','اعثر على إجابات للأسئلة الشائعة حول حلولنا ونموذج التعاون والتنفيذ وخدمات الدعم.')); ?></p><div class="hero-actions"><a class="btn btn-gold" href="<?php echo esc_url(smt_page_url('contact')); ?>"><?php echo esc_html(smt_t('Contact Support','تواصل مع الدعم')); ?></a></div></div><aside class="resource-detail-symbol"><i class="fa-solid fa-circle-question"></i><strong><?php echo esc_html(smt_t('How can we help?','كيف يمكننا مساعدتك؟')); ?></strong><span><?php echo esc_html(smt_t('Sales • Assessment • Service • Support','مبيعات • تقييم • خدمة • دعم')); ?></span></aside></div></section>

  <section class="section"><div class="container faq-layout"><div><?php smt_section_heading(['kicker'=>smt_t('Frequently asked questions','الأسئلة الشائعة'),'title'=>smt_t('Start with a quick answer','ابدأ بإجابة سريعة'),'text'=>smt_t('Open a question below. If your situation is specific, contact our team for direct guidance.','افتح السؤال أدناه. وإذا كانت حالتك محددة فتواصل مع فريقنا للحصول على توجيه مباشر.')]); ?><div class="ui-faq" data-accordion><?php foreach($faqs as $i=>$faq): ?><article class="ui-faq-item"><h3><button type="button" aria-expanded="<?php echo $i===0?'true':'false'; ?>"><span><?php echo esc_html($faq[0]); ?></span><i class="fa-solid fa-plus"></i></button></h3><div class="ui-faq-answer" <?php echo $i===0?'':'hidden'; ?>><p><?php echo esc_html($faq[1]); ?></p></div></article><?php endforeach; ?></div></div><aside class="support-path-card"><span><?php echo esc_html(smt_t('Choose the right path','اختر المسار المناسب')); ?></span><a href="<?php echo esc_url(smt_page_url('contact')); ?>"><i class="fa-solid fa-comments"></i><strong><?php echo esc_html(smt_t('New solution inquiry','استفسار عن حل جديد')); ?></strong><small><?php echo esc_html(smt_t('Discuss needs, assessment, or quotation.','ناقش الاحتياجات أو التقييم أو عرض السعر.')); ?></small></a><a href="<?php echo esc_url(smt_page_url('contact')); ?>"><i class="fa-solid fa-screwdriver-wrench"></i><strong><?php echo esc_html(smt_t('Technical support','الدعم الفني')); ?></strong><small><?php echo esc_html(smt_t('Request maintenance or service assistance.','اطلب مساعدة صيانة أو خدمة.')); ?></small></a><a href="<?php echo esc_url(smt_page_url('technology-assessment')); ?>"><i class="fa-solid fa-clipboard-check"></i><strong><?php echo esc_html(smt_t('Technology assessment','تقييم تقني')); ?></strong><small><?php echo esc_html(smt_t('Build a fact-based improvement roadmap.','ابنِ خارطة تحسين قائمة على البيانات.')); ?></small></a></aside></div></section>

  <section class="ui-cta-section"><div class="container ui-cta-inner"><div><span class="section-kicker light"><?php echo esc_html(smt_t('Still need help?','ما زلت تحتاج إلى مساعدة؟')); ?></span><h2><?php echo esc_html(smt_t('Send your question directly to our team.','أرسل سؤالك مباشرة إلى فريقنا.')); ?></h2></div><div class="ui-cta-actions"><a class="btn btn-gold" href="<?php echo esc_url(smt_page_url('contact')); ?>"><?php echo esc_html(smt_t('Contact Source More','تواصل مع سورس مور')); ?></a></div></div></section>
</main>
<?php get_footer(); ?>
