<?php /* Template Name: Insights */
if (!defined('ABSPATH')) exit;
get_header();
$paged = max(1,(int)get_query_var('paged'));
$args = ['post_type'=>'post','post_status'=>'publish','posts_per_page'=>9,'paged'=>$paged];
if (function_exists('pll_current_language')) $args['lang'] = smt_lang();
$insights = new WP_Query($args);
?>
<main class="resource-detail-page insights-page">
  <section class="ui-page-hero resource-detail-hero"><div class="container resource-detail-hero-grid"><div><span class="eyebrow"><?php echo esc_html(smt_t('Perspectives for better decisions','رؤى لقرارات أفضل')); ?></span><h1><?php echo esc_html(smt_t('Practical technology insights for business leaders.','رؤى تقنية عملية لقادة الأعمال.')); ?></h1><p><?php echo esc_html(smt_t('Explore guidance on cost optimization, managed print, infrastructure, cloud, cybersecurity, workflows, and digital transformation.','استكشف إرشادات حول تحسين التكلفة والطباعة المُدارة والبنية التحتية والسحابة والأمن وسير العمل والتحول الرقمي.')); ?></p></div><aside class="resource-detail-symbol"><i class="fa-solid fa-lightbulb"></i><strong><?php echo esc_html(smt_t('Think clearly. Plan practically.','فكّر بوضوح. وخطط عمليًا.')); ?></strong><span><?php echo esc_html(smt_t('Ideas • Guidance • Decisions • Value','أفكار • إرشاد • قرارات • قيمة')); ?></span></aside></div></section>

  <section class="section"><div class="container"><?php smt_section_heading(['kicker'=>smt_t('Latest insights','أحدث الرؤى'),'title'=>smt_t('Knowledge you can apply','معرفة يمكنك تطبيقها'),'text'=>smt_t('Articles and guidance are published as our knowledge center grows.','يتم نشر المقالات والإرشادات مع نمو مركز المعرفة لدينا.')]); ?><?php if($insights->have_posts()): ?><div class="insights-grid"><?php while($insights->have_posts()): $insights->the_post(); ?><article class="insight-card reveal"><?php if(has_post_thumbnail()): ?><a class="insight-card-image" href="<?php the_permalink(); ?>"><?php the_post_thumbnail('large'); ?></a><?php endif; ?><div class="insight-card-body"><span><?php echo esc_html(get_the_date()); ?></span><h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2><p><?php echo esc_html(wp_trim_words(get_the_excerpt(),24)); ?></p><a class="insight-card-link" href="<?php the_permalink(); ?>"><?php echo esc_html(smt_t('Read insight','اقرأ الرؤية')); ?> <i class="fa-solid fa-arrow-right"></i></a></div></article><?php endwhile; ?></div><div class="insights-pagination"><?php echo wp_kses_post(paginate_links(['total'=>$insights->max_num_pages,'current'=>$paged,'type'=>'list'])); ?></div><?php else: ?><div class="insights-empty"><i class="fa-solid fa-pen-nib"></i><h2><?php echo esc_html(smt_t('Our knowledge center is being prepared.','نعمل على تجهيز مركز المعرفة.')); ?></h2><p><?php echo esc_html(smt_t('Contact our team for guidance on your current technology question.','تواصل مع فريقنا للحصول على إرشاد حول سؤالك التقني الحالي.')); ?></p><a class="btn btn-primary" href="<?php echo esc_url(smt_page_url('contact')); ?>"><?php echo esc_html(smt_t('Ask Our Experts','اسأل خبراءنا')); ?></a></div><?php endif; wp_reset_postdata(); ?></div></section>
</main>
<?php get_footer(); ?>
