<?php
get_header(); the_post();
$id=get_the_ID(); $model=get_post_meta($id,'_smtp_model',true); $type=get_post_meta($id,'_smtp_product_type',true) ?: 'hardware'; $availability=get_post_meta($id,'_smtp_availability',true) ?: 'available'; $mode=get_post_meta($id,'_smtp_price_mode',true) ?: 'quote'; $price=(float)get_post_meta($id,'_smtp_price',true); $brochure=get_post_meta($id,'_smtp_brochure_url',true); $specs=array_filter(array_map('trim',preg_split('/\r\n|\r|\n/',(string)get_post_meta($id,'_smtp_key_specs',true)))); $brands=get_the_terms($id,'smt_product_brand');
$type_labels=['hardware'=>['Hardware','أجهزة'],'software'=>['Software','برمجيات'],'service'=>['Service / Subscription','خدمة / اشتراك']];
$availability_labels=['available'=>['Available','متاح'],'limited'=>['Limited availability','متاح بكمية محدودة'],'pre-order'=>['Pre-order','طلب مسبق'],'on-request'=>['Available on request','متاح عند الطلب'],'out-of-stock'=>['Out of stock','غير متوفر حاليًا']];
$type_pair=$type_labels[$type]??[ucwords(str_replace('-',' ',$type)),ucwords(str_replace('-',' ',$type))];
$availability_pair=$availability_labels[$availability]??[ucwords(str_replace('-',' ',$availability)),ucwords(str_replace('-',' ',$availability))];
?>
<main class="single-product-page"><section class="section product-detail-hero"><div class="container product-detail-grid"><div class="product-gallery"><?php if(has_post_thumbnail()) the_post_thumbnail('large'); else echo '<div class="product-placeholder product-placeholder-large"><i class="fa-solid fa-box-open"></i></div>'; ?></div><div class="product-summary"><div class="product-card-meta"><span><?php echo esc_html(smt_t($type_pair[0],$type_pair[1])); ?></span><span class="availability availability-<?php echo esc_attr($availability); ?>"><?php echo esc_html(smt_t($availability_pair[0],$availability_pair[1])); ?></span></div><h1><?php the_title(); ?></h1><?php if($model): ?><p class="product-model"><?php echo esc_html(smt_t('Model:','الموديل:')); ?> <?php echo esc_html($model); ?></p><?php endif; ?><?php if($brands && !is_wp_error($brands)): ?><p class="product-brand"><?php echo esc_html(smt_t('Brand:','العلامة التجارية:')); ?> <?php echo esc_html(implode(', ',wp_list_pluck($brands,'name'))); ?></p><?php endif; ?><div class="product-excerpt"><?php the_excerpt(); ?></div><?php if($mode==='direct' && $price>0): ?><div class="product-price"><?php echo esc_html(number_format_i18n($price,2)); ?> <?php echo esc_html(smt_t('EGP','جنيه')); ?><small><?php echo esc_html(smt_t('Indicative price, excluding applicable taxes and delivery','سعر استرشادي لا يشمل الضرائب المطبقة أو التوصيل')); ?></small></div><?php else: ?><div class="product-price product-price-quote"><?php echo esc_html(smt_t('Commercial pricing available on request','الأسعار التجارية متاحة عند الطلب')); ?></div><?php endif; ?><div class="product-actions"><a class="btn btn-gold" href="#request-quote"><?php echo esc_html(smt_t('Request a Quote','اطلب عرض سعر')); ?></a><?php if($brochure): ?><a class="btn btn-outline" target="_blank" rel="noopener" href="<?php echo esc_url($brochure); ?>"><?php echo esc_html(smt_t('Download Datasheet','تحميل ورقة المواصفات')); ?></a><?php endif; ?></div></div></div></section>
<section class="section ui-surface-section"><div class="container product-content-grid"><article class="product-description"><h2><?php echo esc_html(smt_t('Product Overview','نظرة عامة على المنتج')); ?></h2><?php the_content(); ?></article><?php if($specs): ?><aside class="product-specifications"><h2><?php echo esc_html(smt_t('Key Specifications','المواصفات الرئيسية')); ?></h2><ul><?php foreach($specs as $spec): ?><li><i class="fa-solid fa-check"></i><?php echo esc_html($spec); ?></li><?php endforeach; ?></ul></aside><?php endif; ?></div></section>
<section class="section" id="request-quote"><div class="container quote-section-grid"><div><h2><?php echo esc_html(smt_t('Request pricing and availability','اطلب السعر والتوافر')); ?></h2><p><?php echo esc_html(smt_t('Tell us your quantity and requirements. Our team will confirm availability, configuration, delivery, support options, and the final commercial offer.','أرسل الكمية والمتطلبات، وسيؤكد فريقنا التوافر والتجهيز والتوصيل وخيارات الدعم والعرض التجاري النهائي.')); ?></p></div><div class="quote-form-card"><?php echo do_shortcode('[source_more_quote_form product_id="'.$id.'"]'); ?></div></div></section></main><?php get_footer(); ?>
